name: Java项目CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    # Use this yaml in your workflow file for each job
    #runs-on: self-hosted
    steps:
    - name: 拉取最新代码
      uses: actions/checkout@v1
    - name: 设置JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: maven依赖缓存        
      uses: actions/cache@v1.0.3
      with:
       path: ./repo
       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
       restore-keys: |
        ${{ runner.os }}-maven-
    - name: maven进行打包
      run: mvn -Pprod package  -f pom.xml -U -B  -T 1C -Dmaven.test.skip=true -Dmaven.compile.fork=true

    - name: 上传发布文件
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./target/sctc_enc-1.0-SNAPSHOT.jar
        asset_name: sctc_enc-1.0-SNAPSHOT.jar
        tag: ${{ github.ref }}
        overwrite: true       
       
